### ISSUE TITLE
Select title component

### ISSUE THREAD

**Issue by serenalau272** [UoaWDCC/wdcc-clubs-mem-checker#45]
### Description
As an `event creator`, I want to `input my desired title for the club checker page` so that `the correct and appropriate information can be displayed to users`.

### Acceptance Criteria
- [x] Users can enter a title in the input field
- [x] The default title is '[club acronym] Membership Checker' and should be the default value in the input field
- [x] The title displayed on the page preview component should always match the text inside the input field
- [x] Users cannot proceed to the next step if the title is empty
- [x] If users attempt to proceed with an empty title, an error should appear under the input field: 'Please enter a title to continue.'
- [x] If the title is not empty, the next button switches component to #46 
- [x] Back button routes back to #21

**Comment by Alam624** [comment]
The current implementation of the shared text field component uses a ref, which makes it a little difficult to bind the context state to the text field data regarding the point
-  The default title is '[club acronym] Membership Checker' and should be the default value in the input field

Maybe clean way to do the two way binding? otherwise may have to change the implementation of the textfield or do something jank

Edit: Decided that it was too much effort to reimplement the textfield component using state instead of ref SO, just pieced together something that seems to work fine for now.
